name: Deploying

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: sh /home/ubuntu/dms-backend/deploy.sh

      - name: sending success build notification to slack
        if: success()
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: 0240CCALMA
          status: SUCCESS
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}

      - name: sending failure build notification to slack
        if: failure()
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: 0240CCALMA
          status: FAILURE
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
